### Cross Validation

Cross validation helps for extra checking on accuracy of models.

For this the train data will be splitted into 'n' number of samples and will check the accuracy score with each sample. If the accuracy score of each sample looks almost simillar (standard deviation near to zero), model will be a good model. If the accuracy is much more different for each samples, the model is not that good.

K Fold technique will help to check if all of our samples are in same accuracy range or different.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
df = pd.read_csv(r'D:\E\Courses\Edureka\Social_Network_Ads.csv')

In [4]:
print(df.shape)
df.head(3)

(400, 5)


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [8]:
x = df.iloc[:, [2,3]].values

In [11]:
y = df.iloc[:, 4].values

In [12]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [13]:
from sklearn.svm import SVC

classifier_model = SVC(kernel='rbf')
classifier_model.fit(x_train, y_train)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [14]:
y_pred = classifier_model.predict(x_test)

In [15]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [17]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[49  3]
 [21  7]]
0.7


##### Cross validation will help to check the accuracy further (a second opinion)

In [18]:
#applying K flod technique over the model we have created.

from sklearn.model_selection import cross_val_score

accuracies = cross_val_score(estimator=classifier_model, X=x_train, y=y_train, cv=10)   # cv=10 means 10 samples will be created

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureW

In [19]:
accuracies

array([0.60606061, 0.6969697 , 0.63636364, 0.66666667, 0.60606061,
       0.64516129, 0.67741935, 0.67741935, 0.67741935, 0.70967742])

In [20]:
accuracies.mean()

0.6599217986314762

In [21]:
accuracies.std()

# standard deviation should be as low as possible

0.033744734366448675

###### As there is no high variation between accuracy score of each sample, it looks tobe a very good sample.

Notes:-
- Cross validation with 10 samples is most common.
- If we have a huge dataset, we can have arounf 15 to 20% data in each sample.