## pickle

Using pickle we can save the created model as a file to avoid creating it multiple times or by multiple users.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'area':[2600, 3000, 3200, 3600, 4000], 'price':[550000, 565000, 610000, 680000, 725000]})

In [3]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [10]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
model.coef_

array([135.78767123])

In [12]:
model.intercept_

180616.43835616432

In [13]:
model.predict([[5000]])

array([859554.79452055])

In [16]:
import os

In [17]:
os.chdir(r'D:\E\Courses\Edureka')

In [14]:
import pickle

In [18]:
# saving the model in a file

with open('model_pickle', 'wb') as file:
    pickle.dump(model, file)

In [19]:
with open('model_pickle', 'rb') as file:
    mp = pickle.load(file)

In [20]:
mp.coef_

array([135.78767123])

In [21]:
mp.intercept_

180616.43835616432

In [22]:
mp.predict([[5000]])

array([859554.79452055])