### Liniar Regression

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r'D:\Edureka\dataset_for_leniar_regresion.xlsx', sheet_name='Sheet1')

In [3]:
print(df.shape)
df.head()

(25, 2)


Years_exp  Salary
0        1.1   39343
1        1.3   46205
2        1.5   37731
3        2.0   43525
4        2.2   39891

In [4]:
x = df.iloc[:, 0:1].values

In [5]:
x

array([[1.1],
       [1.3],
       [1.5],
       [2. ],
       [2.2],
       [2.9],
       [3. ],
       [3.2],
       [3.2],
       [3.7],
       [3.9],
       [4. ],
       [4. ],
       [4.1],
       [4.5],
       [4.9],
       [5.1],
       [5.3],
       [5.9],
       [6. ],
       [6.8],
       [7.1],
       [7.5],
       [7.8],
       [9. ]])

In [6]:
y = df.iloc[:,-1:].values
y

array([[ 39343],
       [ 46205],
       [ 37731],
       [ 43525],
       [ 39891],
       [ 56642],
       [ 60150],
       [ 54445],
       [ 64445],
       [ 57189],
       [ 63218],
       [ 55794],
       [ 56957],
       [ 57081],
       [ 61111],
       [ 67938],
       [ 66029],
       [ 83088],
       [ 81363],
       [ 93940],
       [ 91738],
       [ 98273],
       [100000],
       [102000],
       [110000]], dtype=int64)

####### Supervised Learning

In [7]:
from sklearn.model_selection import train_test_split

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

#we do not prefer train data ercentage less than 50%

In [30]:
print(len(x_train), len(x_test), len(y_train), len(y_test))

17 8 17 8


In [31]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [32]:
y_pred = linear_model.predict(x_test)

In [33]:
y_pred

array([[ 53116.58565669],
       [ 39990.50001902],
       [ 82181.48956867],
       [ 73743.29165874],
       [ 63429.93865772],
       [ 96245.15275189],
       [ 75618.44674984],
       [110308.81593511]])

In [34]:
from sklearn.metrics import r2_score

In [36]:
r2_score(y_test, y_pred)   # R^2 value more than 95% - will be a good model

0.9227543667706939

In [37]:
linear_model.coef_     #to find slope of line (m)

array([[9375.77545548]])

In [38]:
linear_model.intercept_    # to find constant (c)

array([25926.8368358])

###### mean the exuation is --->   y = 10201*Experience + 23060

In [39]:
new_exp = pd.read_excel(r'D:\Edureka\dataset_for_leniar_regresion.xlsx', sheet_name='salary_to_predict')

In [40]:
new_exp['predicted_salary'] = linear_model.predict(new_exp)

In [41]:
new_exp

Years_exp  predicted_salary
0        0.0      25926.836836
1        2.0      44678.387747
2        3.0      54054.163202
3        3.6      59679.628476
4       10.0     119684.591391