# Grid Search Algorithm

####### Grid search algorithm will help to identify which parameters are best to apply to predict with other algorithms.

Trying to predict if customer will buy the product or not using different classification algorithm and then applyting grid search algorithm to know which parameters are best to predict.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv(r'D:\Courses\Edureka\Social_Network_Ads.csv')

In [3]:
print(df.shape)
df.head(2)

(400, 5)


User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [4]:
x = df.iloc[:, [2,3]].values

In [5]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [6]:
# as we apply KNN classification algorithm need to apply standardscalar to x (to make both independant variables in same scale)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [7]:
x

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [8]:
y = df.iloc[:,4].values

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=99)

####### applying support vector machine classification algorithm to predict if customer will purchase product

In [12]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='sigmoid')
classifier_svm.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier()
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [14]:
y_predict_svm = classifier_svm.predict(x_test)

In [15]:
y_predict_knn = classifier_knn.predict(x_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_predict_svm))
accuracy_score(y_test, y_predict_svm)

[[61 22]
 [17 20]]


0.675

In [18]:
print(confusion_matrix(y_test, y_predict_knn))
accuracy_score(y_test, y_predict_knn)

[[78  5]
 [ 6 31]]


0.9083333333333333

###### applying grid search algorithm on SVM to check which parameter can give better accuracy score

In [25]:
from sklearn.model_selection import GridSearchCV

parameters = [{'C':[2,3,4,5,6,7], 'kernel':['sigmoid', 'rbf', 'linear']}]  # grid search will check for these parameters

In [26]:
grid_search = GridSearchCV(estimator=classifier_svm, param_grid=parameters,
                          scoring='accuracy', n_jobs=-1)

# estimator - checking for which algorithm, parameter_grid - for which parameters we have to check best accuracy
# scoring - accuracy score, n_jobs=-1 means entire CPU dedicating forthis process

grid_search = grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

In [27]:
best_accuracy

0.9035714285714285

In [28]:
best_parameters

{'C': 4, 'kernel': 'rbf'}

In [29]:
# best is with 4 is the best number and kernel is rbf

###### applying grid search algorithm on KNN to check which parameter can give better accuracy score

In [39]:
lst = list(range(1,100))

In [41]:
from sklearn.model_selection import GridSearchCV

parameters = [{'n_neighbors':lst}]

In [42]:
grid_search = GridSearchCV(estimator=classifier_knn, param_grid=parameters, scoring='accuracy', n_jobs=-1)
grid_search = grid_search.fit(x_train, y_train)

In [43]:
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

In [44]:
best_accuracy

0.9071428571428571

In [45]:
best_parameters

{'n_neighbors': 11}

####### The best accuracy is with n_neighbors as 11 . (If its a even number, we can go with next or previous number to go with odd)