## XG Boost

XG boost use to improve the speed of the models. In the practical scinarios with huge dataset and if time is in consideration, this will be helpful. This can use in regression and classification models.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [4]:
df = pd.read_csv(r'D:\E\Courses\Edureka\Churn_Modelling.csv')

In [5]:
print(df.shape)
df.head()

(10000, 14)


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
# defining dependant and independant variables

x = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [12]:
# As Geography and Gender is categorical variables applying encoding

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [14]:
le = LabelEncoder()
x[:, 1] = le.fit_transform(x[:, 1])

In [15]:
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [16]:
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [17]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [18]:
ohe = OneHotEncoder(categorical_features=[1])
x = ohe.fit_transform(x).toarray()

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [20]:
pd.DataFrame(x)

0    1    2      3    4     5     6          7    8    9   10  \
0     1.0  0.0  0.0  619.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0   
1     0.0  0.0  1.0  608.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0   
2     1.0  0.0  0.0  502.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0   
3     1.0  0.0  0.0  699.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   
4     0.0  0.0  1.0  850.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   
...   ...  ...  ...    ...  ...   ...   ...        ...  ...  ...  ...   
9995  1.0  0.0  0.0  771.0  1.0  39.0   5.0       0.00  2.0  1.0  0.0   
9996  1.0  0.0  0.0  516.0  1.0  35.0  10.0   57369.61  1.0  1.0  1.0   
9997  1.0  0.0  0.0  709.0  0.0  36.0   7.0       0.00  1.0  0.0  1.0   
9998  0.0  1.0  0.0  772.0  1.0  42.0   3.0   75075.31  2.0  1.0  0.0   
9999  1.0  0.0  0.0  792.0  0.0  28.0   4.0  130142.79  1.0  1.0  0.0   

             11  
0     101348.88  
1     112542.58  
2     113931.57  
3      93826.63  
4      79084.10  
...         ...  
9995   96270.64  
9996  101699.77  
9997   42085.58  
9998   92888.52  
9999   38190.78  

[10000 rows x 12 columns]

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [23]:
# applying KNN classifier for exit prediction

from sklearn.neighbors import KNeighborsClassifier

In [24]:
classifier_knn = KNeighborsClassifier(n_neighbors=5, p=2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [26]:
y_pred = classifier_knn.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [28]:
confusion_matrix(y_test, y_pred)

array([[1483,  112],
       [ 359,   46]], dtype=int64)

In [29]:
accuracy_score(y_test, y_pred)

0.7645

In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86      1595
           1       0.29      0.11      0.16       405

    accuracy                           0.76      2000
   macro avg       0.55      0.52      0.51      2000
weighted avg       0.70      0.76      0.72      2000



##### xgboost is a new package (comment on Apr'20). So lot of options are not available in the same. In xgboost, we can run only a few agorithms. By default it executes decision tree. We can change it to random forest or logistic regression. Algorithims like KNN are not available in xgboost.

(-comment on 02-Apr-2020)

In [31]:
from xgboost import XGBClassifier
xgb_classifier = XGBClassifier()
xgb_classifier.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [32]:
y_pred_xgb = xgb_classifier.predict(x_test)

In [33]:
confusion_matrix(y_test, y_pred_xgb)

array([[1497,   98],
       [ 196,  209]], dtype=int64)

In [34]:
accuracy_score(y_test, y_pred_xgb)

0.853

In [36]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91      1595
           1       0.68      0.52      0.59       405

    accuracy                           0.85      2000
   macro avg       0.78      0.73      0.75      2000
weighted avg       0.84      0.85      0.85      2000



In [37]:
#applying cross validation with k-fold into the xgb_classifier

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=xgb_classifier, X=x_train, y=y_train, cv=10)
accuracies.mean()

0.8530042836004432

In [39]:
accuracies.std()

0.01238685691299341

In [40]:
accuracies

array([0.85892634, 0.83146067, 0.86625   , 0.84375   , 0.83875   ,
       0.85125   , 0.8675    , 0.8475    , 0.85356696, 0.87108886])

#### accracies are closer and standard deviation is small. so the model looks good.

As this is 10k dataset, the speed is not that visible. On huge dataset it will be more visible

In [41]:
# to run random forest classifier on xgboost
from xgboost import XGBRFClassifier