In [1]:
# decision tree & random forest

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r'D:\Edureka\50_Startups.csv')
print(df.shape)
df.head(2)

(50, 5)


R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [5]:
x = df.iloc[:, 1:2].values

In [6]:
y = df.iloc[:, -1:].values

y[:2]

array([[192261.83],
       [191792.06]])

In [8]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [9]:
x_train = np.append(arr=x_train, values = np.ones((35,1)).astype(int), axis=1)

In [11]:
pd.DataFrame(x_train).head(2)

0    1
0  122782.75  1.0
1   65947.93  1.0

In [12]:
import statsmodels.api as sm

In [13]:
regressor_OLS = sm.OLS(endog=y_train , exog=x_train).fit()

In [14]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.043
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     1.485
Date:                Wed, 12 Feb 2020   Prob (F-statistic):              0.232
Time:                        11:38:39   Log-Likelihood:                -416.38
No. Observations:                  35   AIC:                             836.8
Df Residuals:                      33   BIC:                             839.9
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.2517      0.207      1.218      0.232      -0.169       0.672
const       7.978e+04   2.61e+04      3.056      0.004    2.67e+04    1.33e+05
==============================================================================
Omnibus:                        3.059   Durbin-Watson:                   1.637
Prob(Omnibus):                  0.217   Jarque-Bera (JB):                2.003
Skew:                           0.566   Prob(JB):                        0.367
Kurtosis:                       3.306   Cond. No.                     5.34e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.34e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

####### Considering R^2 value and P-value, we cannot got with linear regression.

In [39]:
y_predict_lin = regressor_OLS.predict(x_test)

### Decision Tree (Regression)

In [15]:
from sklearn.tree import DecisionTreeRegressor

reg_dec_tree = DecisionTreeRegressor()
reg_dec_tree.fit(x_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [16]:
x_test = np.append(arr=x_test, values=np.ones((15,1)).astype(int), axis=1)

In [18]:
y_predit = reg_dec_tree.predict(x_test)

In [20]:
y_predit

array([ 42559.73,  77798.83, 111313.02,  99937.59, 118474.03,  97483.56,
       141585.52,  96479.51, 118474.03, 141585.52, 125370.37, 108552.04,
        96479.51, 108733.99,  99937.59])

In [21]:
y_test

array([[134307.35],
       [ 81005.76],
       [122776.86],
       [ 14681.4 ],
       [146121.95],
       [191792.06],
       [ 69758.98],
       [144259.4 ],
       [124266.9 ],
       [105008.31],
       [155752.6 ],
       [ 71498.49],
       [166187.94],
       [149759.96],
       [ 49490.75]])

In [22]:
# to check the accuracy of decision tree, we can check RMSE (Root Mean Square Error)

# RMSE  = sqrt((Yactual - Ypredicted)^2/n)

In [23]:
output = pd.concat([pd.DataFrame(y_predit), pd.DataFrame(y_test)], axis=1)

In [24]:
output

0          0
0    42559.73  134307.35
1    77798.83   81005.76
2   111313.02  122776.86
3    99937.59   14681.40
4   118474.03  146121.95
5    97483.56  191792.06
6   141585.52   69758.98
7    96479.51  144259.40
8   118474.03  124266.90
9   141585.52  105008.31
10  125370.37  155752.60
11  108552.04   71498.49
12   96479.51  166187.94
13  108733.99  149759.96
14   99937.59   49490.75

In [25]:
output.columns = ['predicted', 'test_actual']

In [26]:
output

predicted  test_actual
0    42559.73    134307.35
1    77798.83     81005.76
2   111313.02    122776.86
3    99937.59     14681.40
4   118474.03    146121.95
5    97483.56    191792.06
6   141585.52     69758.98
7    96479.51    144259.40
8   118474.03    124266.90
9   141585.52    105008.31
10  125370.37    155752.60
11  108552.04     71498.49
12   96479.51    166187.94
13  108733.99    149759.96
14   99937.59     49490.75

In [27]:
output['difference'] = output.predicted - output.test_actual

In [29]:
output.head(2)

predicted  test_actual  difference
0   42559.73    134307.35   -91747.62
1   77798.83     81005.76    -3206.93

In [30]:
output['square'] = output.difference * output.difference

In [31]:
output.head(2)

predicted  test_actual  difference        square
0   42559.73    134307.35   -91747.62  8.417626e+09
1   77798.83     81005.76    -3206.93  1.028440e+07

In [37]:
# RMSE (Root Mean Squared Error)

np.sqrt(sum(output['square'])/len(output))

55186.467134010854

In [41]:
# RMSE for the linear regression model

output_lin = pd.concat([pd.DataFrame(y_predict_lin), pd.DataFrame(y_test)], axis=1)

In [42]:
output_lin.head(2)

0          0
0  113883.985040  134307.35
1  100665.951187   81005.76

In [43]:
output_lin.columns = ['predicted', 'test_actual']

In [44]:
output_lin.head(2)

predicted  test_actual
0  113883.985040    134307.35
1  100665.951187     81005.76

In [45]:
output_lin['difference'] = output_lin.predicted - output_lin.test_actual
output_lin['square'] = output_lin.difference * output_lin.difference
np.sqrt(sum(output_lin['square'])/len(output_lin))

46518.581926236504

######## In ideal cases, decision tree gives better RMSE, in above example its for linear regression.

#### Random Forest

In [47]:
from sklearn.ensemble import RandomForestRegressor

#decision tree will be running inside random forest. One model running inside another model is known as ensemble

In [70]:
regressor_rf = RandomForestRegressor(n_estimators=3)  # means create 3 samples are creating and running inside rendom forest

In [71]:
regressor_rf.fit(x_train, y_train)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [72]:
y_predit_rf = regressor_rf.predict(x_test)

In [73]:
for i in range(len(y_test)):
    print(y_test[i], y_predit_rf[i])

[134307.35] 42559.73
[81005.76] 84025.72333333333
[122776.86] 103267.07333333332
[14681.4] 98883.84333333334
[146121.95] 118474.02999999998
[191792.06] 98657.25333333334
[69758.98] 124626.40999999999
[144259.4] 90252.61666666665
[124266.9] 118474.02999999998
[105008.31] 124626.40999999999
[155752.6] 125370.37
[71498.49] 124698.39999999998
[166187.94] 90252.61666666665
[149759.96] 111980.67
[49490.75] 112295.21666666667


In [74]:
output_rf = pd.concat([pd.DataFrame(y_predit_rf), pd.DataFrame(y_test)], axis=1)

In [75]:
output_rf.columns = ['predicted', 'test_actual']

In [76]:
# RMSE value

output_rf['difference'] = output_rf.predicted - output_rf.test_actual
output_rf['square'] = output_rf.difference * output_rf.difference
np.sqrt(sum(output_rf['square'])/len(output_rf))

55721.14083386888