In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv(r'E:\classification\cricket_odi_data_kaggle\ContinousDataset.csv')

In [3]:
df.head()

Unnamed: 0 Scorecard       Team 1     Team 2           Margin  \
0           0   ODI # 1    Australia    England  Winner2ndInning   
1           1   ODI # 2      England  Australia  Winner2ndInning   
2           2   ODI # 3      England  Australia  Winner2ndInning   
3           3   ODI # 4      England  Australia  Winner2ndInning   
4           4   ODI # 5  New Zealand   Pakistan  Winner1stInning   

         Ground    Match Date       Winner Host_Country Venue_Team1  \
0     Melbourne   Jan 5, 1971    Australia    Australia        Home   
1    Manchester  Aug 24, 1972      England      England        Home   
2        Lord's  Aug 26, 1972    Australia      England        Home   
3    Birmingham  Aug 28, 1972      England      England        Home   
4  Christchurch  Feb 11, 1973  New Zealand  New Zealand        Home   

  Venue_Team2 Innings_Team1 Innings_Team2  
0        Away        Second         First  
1        Away        Second         First  
2        Away         First        Second  
3        Away        Second         First  
4        Away         First        Second

In [6]:
df.shape

(7494, 13)

In [5]:
df.isna().sum()

Unnamed: 0         0
Scorecard          0
Team 1             0
Team 2             0
Margin             0
Ground             0
Match Date         0
Winner             0
Host_Country     130
Venue_Team1        0
Venue_Team2        0
Innings_Team1      0
Innings_Team2      0
dtype: int64

In [9]:
df.dropna(axis=0, inplace=True)

In [10]:
df.isna().sum()

Unnamed: 0       0
Scorecard        0
Team 1           0
Team 2           0
Margin           0
Ground           0
Match Date       0
Winner           0
Host_Country     0
Venue_Team1      0
Venue_Team2      0
Innings_Team1    0
Innings_Team2    0
dtype: int64

In [11]:
df.columns = df.columns.str.replace(' ', '_')

In [12]:
df.columns

Index(['Unnamed:_0', 'Scorecard', 'Team_1', 'Team_2', 'Margin', 'Ground',
       'Match_Date', 'Winner', 'Host_Country', 'Venue_Team1', 'Venue_Team2',
       'Innings_Team1', 'Innings_Team2'],
      dtype='object')

In [14]:
df = df[['Team_1', 'Team_2', 'Ground', 'Host_Country', 'Venue_Team1', 'Innings_Team1', 'Winner']]

In [15]:
df2 = df.copy()

In [16]:
df2.head(1)

Team_1   Team_2     Ground Host_Country Venue_Team1 Innings_Team1  \
0  Australia  England  Melbourne    Australia        Home        Second   

      Winner  
0  Australia

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for i in df.columns:
    df[i] = le.fit_transform(df[i])

<ipython-input-18-7c3799764db4>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i] = le.fit_transform(df[i])


In [20]:
df.head()

Team_1  Team_2  Ground  Host_Country  Venue_Team1  Innings_Team1  Winner
0       1       6      95             0            1              1       1
1       6       1      93             3            1              1       6
2       6       1      91             3            1              0       1
3       6       1      16             3            1              1       6
4      13      15      35            10            1              0      13

In [21]:
df.Team_1.value_counts()

8     855
1     850
15    832
18    737
21    725
13    677
6     660
17    545
22    469
2     325
10    149
9     112
16     87
0      81
4      75
12     71
3      36
19     35
7      18
14     10
11      8
5       4
20      3
Name: Team_1, dtype: int64

In [23]:
df2.Team_1.value_counts()

India           855
Australia       850
Pakistan        832
Sri Lanka       737
West Indies     725
New Zealand     677
England         660
South Africa    545
Zimbabwe        469
Bangladesh      325
Kenya           149
Ireland         112
Scotland         87
Afghanistan      81
Canada           75
Netherlands      71
Bermuda          36
U.A.E.           35
Hong Kong        18
P.N.G.           10
Namibia           8
East Africa       4
U.S.A.            3
Name: Team_1, dtype: int64

In [25]:
comb_df = pd.concat([df,df2], axis=1)

In [28]:
comb_df.to_csv(r'E:\classification\cricket_odi_data_kaggle\data_reference.csv')

In [30]:
df.shape

(7364, 7)

In [34]:
x = df.iloc[:, :6].values
y = df.iloc[:, 6].values

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x , y, random_state=1, test_size=0.25)

In [36]:
len(x_train), len(x_test), len(y_train), len(y_test)

(5523, 1841, 5523, 1841)

#### xgboost

In [38]:
!pip install xgboost

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\pip-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\cli\main.py", line 75, in main
    return command.main(cmd_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 114, in main
    return self._main(args)
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_internal\cli\command_context.py", line 28, in main_context
    yield
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\contextlib2.py", line 479, in __exit__
    _reraise_with_existing_context(exc_details)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\contextlib2.py", line 340, in _reraise_with_existing_context
    raise exc_details[1]
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 131, in __exit__
    self.g

In [39]:
from xgboost import XGBClassifier

xgbc = XGBClassifier()
xgbc.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [40]:
y_pred_xgbc = xgbc.predict(x_test)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [42]:
accuracy_score(y_test, y_pred_xgbc)

0.6349809885931559

In [46]:
#india vs australia match on 29th Nov predition
xgbc.predict(np.array([[1,8,140,0,1,0]]))

array([1])

In [47]:
# south africa vs england match on 29th Nov predition (exact venue not available)
xgbc.predict(np.array([[17,6,17,14,1,0]]))

array([6])

In [52]:
from xgboost import XGBRFClassifier
xgbrf = XGBRFClassifier(num_parallel_tree=20)
xgbrf.fit(x_train, y_train)

XGBRFClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
                colsample_bytree=1, gamma=0, gpu_id=-1, importance_type='gain',
                interaction_constraints='', max_delta_step=0, max_depth=6,
                min_child_weight=1, missing=nan, monotone_constraints='()',
                n_estimators=100, n_jobs=0, num_parallel_tree=20,
                objective='multi:softprob', random_state=0, reg_alpha=0,
                scale_pos_weight=None, tree_method='exact',
                validate_parameters=1, verbosity=None)

In [53]:
y_pred_xgbrf = xgbrf.predict(x_test)

In [54]:
accuracy_score(y_test, y_pred_xgbrf)

0.6480173818576861

In [55]:
#india vs australia match on 29th Nov predition
xgbrf.predict(np.array([[1,8,140,0,1,0]]))

array([1])

In [56]:
# south africa vs england match on 29th Nov predition (exact venue not available)
xgbrf.predict(np.array([[17,6,17,14,1,0]]))

array([17])

#### trying grid search over xgbrf

In [57]:
from sklearn.model_selection import GridSearchCV
param = [{'num_parallel_tree':list(range(2,101)), 'importance_type':["gain", "weight", "cover", "total_gain", "total_cover"]}]

In [58]:
grid_search = GridSearchCV(estimator=xgbrf, param_grid=param, n_jobs=-1, scoring='accuracy')
grid_search = grid_search.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [59]:
best_score = grid_search.best_score_
best_param = grid_search.best_params_

In [60]:
best_score, best_param

(0.6378774017968392, {'importance_type': 'gain', 'num_parallel_tree': 2})

##### catboost

In [49]:
!pip install catboost

In [61]:
from catboost import CatBoostClassifier
cbc = CatBoostClassifier()
cbc.fit(x_train, y_train)

Learning rate set to 0.086332
0:	learn: 2.8011388	total: 156ms	remaining: 2m 35s
1:	learn: 2.5938644	total: 191ms	remaining: 1m 35s
2:	learn: 2.4527054	total: 226ms	remaining: 1m 15s
3:	learn: 2.3163460	total: 258ms	remaining: 1m 4s
4:	learn: 2.2045662	total: 290ms	remaining: 57.6s
5:	learn: 2.1132438	total: 321ms	remaining: 53.2s
6:	learn: 2.0278434	total: 355ms	remaining: 50.3s
7:	learn: 1.9727365	total: 386ms	remaining: 47.8s
8:	learn: 1.9206856	total: 419ms	remaining: 46.2s
9:	learn: 1.8439777	total: 451ms	remaining: 44.6s
10:	learn: 1.7931744	total: 482ms	remaining: 43.3s
11:	learn: 1.7432439	total: 518ms	remaining: 42.7s
12:	learn: 1.6846471	total: 551ms	remaining: 41.8s
13:	learn: 1.6380644	total: 587ms	remaining: 41.3s
14:	learn: 1.5936523	total: 618ms	remaining: 40.6s
15:	learn: 1.5521432	total: 649ms	remaining: 39.9s
16:	learn: 1.5253591	total: 685ms	remaining: 39.6s
17:	learn: 1.5058438	total: 702ms	remaining: 38.3s
18:	learn: 1.4781632	total: 737ms	remaining: 38.1s
19:	lear

In [62]:
y_pred_cbc = cbc.predict(x_test)

In [63]:
accuracy_score(y_test, y_pred_cbc)

0.6252036936447583

In [64]:
#india vs australia match on 29th Nov predition
cbc.predict(np.array([[1,8,140,0,1,0]]))

array([[1]], dtype=int64)

In [65]:
# south africa vs england match on 29th Nov predition (exact venue not available)
cbc.predict(np.array([[17,6,17,14,1,0]]))

array([[6]], dtype=int64)