In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')

In [4]:
df.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
df = df[['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare','sex',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone']]

In [7]:
df.deck.value_counts()

C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: deck, dtype: int64

In [8]:
df.isna().sum()

survived         0
pclass           0
age            177
sibsp            0
parch            0
fare             0
sex              0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [9]:
df.drop(columns=['deck'], inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [10]:
df.head()

survived  pclass   age  sibsp  parch     fare     sex embarked  class  \
0         0       3  22.0      1      0   7.2500    male        S  Third   
1         1       1  38.0      1      0  71.2833  female        C  First   
2         1       3  26.0      0      0   7.9250  female        S  Third   
3         1       1  35.0      1      0  53.1000  female        S  First   
4         0       3  35.0      0      0   8.0500    male        S  Third   

     who  adult_male  embark_town alive  alone  
0    man        True  Southampton    no  False  
1  woman       False    Cherbourg   yes  False  
2  woman       False  Southampton   yes   True  
3  woman       False  Southampton   yes  False  
4    man        True  Southampton    no   True

In [14]:
df['age'] = df['age'].fillna(round(df['age'].mean(),2))

<ipython-input-14-83c78ecd3605>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].fillna(round(df['age'].mean(),2))


In [15]:
df.isna().sum()

survived       0
pclass         0
age            0
sibsp          0
parch          0
fare           0
sex            0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [25]:
df['embarked'].fillna(df.embarked.mode()[0], inplace=True)  # sometime mode returns more than 1 value

In [26]:
df['embark_town'].fillna(df.embark_town.mode()[0], inplace=True)  # sometime mode returns more than 1 value

In [27]:
df.isna().sum()

survived       0
pclass         0
age            0
sibsp          0
parch          0
fare           0
sex            0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [28]:
df.head(1)

survived  pclass   age  sibsp  parch  fare   sex embarked  class  who  \
0         0       3  22.0      1      0  7.25  male        S  Third  man   

   adult_male  embark_town alive  alone  
0        True  Southampton    no  False

In [29]:
df.shape

(891, 14)

In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [37]:
for i in range(6,14):
    df.iloc[:, i] = le.fit_transform(df.iloc[:, i])

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [38]:
df.head()

survived  pclass   age  sibsp  parch     fare  sex  embarked  class  who  \
0         0       3  22.0      1      0   7.2500    1         2      2    1   
1         1       1  38.0      1      0  71.2833    0         0      0    2   
2         1       3  26.0      0      0   7.9250    0         2      2    2   
3         1       1  35.0      1      0  53.1000    0         2      0    2   
4         0       3  35.0      0      0   8.0500    1         2      2    1   

   adult_male  embark_town  alive  alone  
0           1            2      0      0  
1           0            0      1      0  
2           0            2      1      1  
3           0            2      1      0  
4           1            2      0      1

In [39]:
df.shape

(891, 14)

In [46]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [47]:
x,y

(     pclass   age  sibsp  parch     fare  sex  embarked  class  who  \
 0         3  22.0      1      0   7.2500    1         2      2    1   
 1         1  38.0      1      0  71.2833    0         0      0    2   
 2         3  26.0      0      0   7.9250    0         2      2    2   
 3         1  35.0      1      0  53.1000    0         2      0    2   
 4         3  35.0      0      0   8.0500    1         2      2    1   
 ..      ...   ...    ...    ...      ...  ...       ...    ...  ...   
 886       2  27.0      0      0  13.0000    1         2      1    1   
 887       1  19.0      0      0  30.0000    0         2      0    2   
 888       3  29.7      1      2  23.4500    0         2      2    2   
 889       1  26.0      0      0  30.0000    1         0      0    1   
 890       3  32.0      0      0   7.7500    1         1      2    1   
 
      adult_male  embark_town  alive  alone  
 0             1            2      0      0  
 1             0            0      1      

In [48]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=0, stratify=y)

In [49]:
len(x_train), len(x_test), len(y_train), len(y_test)

(668, 223, 668, 223)

##### applying logistic regression

In [50]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [52]:
y_pred_lr = lr.predict(x_test)

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [54]:
confusion_matrix(y_test, y_pred_lr)

array([[137,   0],
       [  0,  86]], dtype=int64)

In [55]:
accuracy_score(y_test, y_pred_lr)

1.0

##### applying decision tree

In [60]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion='entropy', splitter='random')
dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', splitter='random')

In [61]:
y_pred_dt = dt.predict(x_test)

In [62]:
confusion_matrix(y_test, y_pred_dt)

array([[137,   0],
       [  0,  86]], dtype=int64)

In [63]:
accuracy_score(y_test, y_pred_dt)

1.0

##### applying random forest

In [64]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10)
rf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=10)

In [65]:
y_pred_rf = rf.predict(x_test)

In [66]:
confusion_matrix(y_test, y_pred_rf)

array([[137,   0],
       [  0,  86]], dtype=int64)

##### applying naive bayes

In [67]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [69]:
y_pred_gnb = gnb.predict(x_test)

In [70]:
confusion_matrix(y_test, y_pred_gnb)

array([[137,   0],
       [  0,  86]], dtype=int64)

##### applying SVM (kernel='rbf')

In [74]:
from sklearn.svm import SVC
sv = SVC(kernel='rbf')
sv.fit(x_train, y_train)

SVC()

In [75]:
y_pred_sv = sv.predict(x_test)

In [76]:
confusion_matrix(y_test, y_pred_sv)

array([[122,  15],
       [ 65,  21]], dtype=int64)

In [77]:
accuracy_score(y_test, y_pred_sv)

0.6412556053811659

##### applying SVM (kernel='linear')

In [78]:
from sklearn.svm import SVC
sv = SVC(kernel='linear')
sv.fit(x_train, y_train)
y_pred_sv = sv.predict(x_test)
confusion_matrix(y_test, y_pred_sv)

array([[137,   0],
       [  0,  86]], dtype=int64)

##### applying SVM (kernel='poly')

In [79]:
from sklearn.svm import SVC
sv = SVC(kernel='poly')
sv.fit(x_train, y_train)
y_pred_sv = sv.predict(x_test)
confusion_matrix(y_test, y_pred_sv)

array([[135,   2],
       [ 74,  12]], dtype=int64)

##### applying SVM (kernel='sigmoid')

In [80]:
from sklearn.svm import SVC
sv = SVC(kernel='sigmoid')
sv.fit(x_train, y_train)
y_pred_sv = sv.predict(x_test)
confusion_matrix(y_test, y_pred_sv)

array([[85, 52],
       [38, 48]], dtype=int64)

#### applying KNN

In [81]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [82]:
y_pred_knn = knn.predict(x_test)

In [83]:
confusion_matrix(y_test, y_pred_knn)

array([[112,  25],
       [ 33,  53]], dtype=int64)

In [91]:
accuracy_score(y_test, y_pred_knn)

0.7399103139013453

#### applying Grid search over svc

In [84]:
from sklearn.model_selection import GridSearchCV
param = [{'kernel':['sigmoid', 'poly', 'rbf', 'linear'], 'C':[1,2,3,4]}]
grid_search = GridSearchCV(estimator=sv, param_grid=param, scoring='accuracy')
grid_search = grid_search.fit(x_train, y_train)

In [85]:
best_score = grid_search.best_score_
best_param = grid_search.best_params_

In [86]:
best_score

1.0

In [87]:
best_param

{'C': 1, 'kernel': 'linear'}

##### applying cross validation

In [88]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=knn, X=x_train, y=y_train, cv=10)

In [89]:
accuracies

array([0.80597015, 0.71641791, 0.76119403, 0.70149254, 0.8358209 ,
       0.82089552, 0.73134328, 0.86567164, 0.78787879, 0.75757576])

In [90]:
accuracies.mean()

0.7784260515603799