In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
df = pd.read_csv(r'D:\E\Courses\ML_Practice\ODI_Cricket_data.csv')

In [3]:
print(df.shape)
df.head(2)

(7494, 13)


Unnamed: 0 Scorecard     Team 1     Team 2           Margin      Ground  \
0           0   ODI # 1  Australia    England  Winner2ndInning   Melbourne   
1           1   ODI # 2    England  Australia  Winner2ndInning  Manchester   

  Match Date     Winner Host_Country Venue_Team1 Venue_Team2 Innings_Team1  \
0  05-Jan-71  Australia    Australia        Home        Away        Second   
1  24-Aug-72    England      England        Home        Away        Second   

  Innings_Team2  
0         First  
1         First

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7494 entries, 0 to 7493
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Unnamed: 0     7494 non-null   int64 
 1   Scorecard      7494 non-null   object
 2   Team 1         7494 non-null   object
 3   Team 2         7494 non-null   object
 4   Margin         7494 non-null   object
 5   Ground         7494 non-null   object
 6   Match Date     7494 non-null   object
 7   Winner         7494 non-null   object
 8   Host_Country   7494 non-null   object
 9   Venue_Team1    7494 non-null   object
 10  Venue_Team2    7494 non-null   object
 11  Innings_Team1  7494 non-null   object
 12  Innings_Team2  7494 non-null   object
dtypes: int64(1), object(12)
memory usage: 761.2+ KB


In [5]:
df.isna().sum()

Unnamed: 0       0
Scorecard        0
Team 1           0
Team 2           0
Margin           0
Ground           0
Match Date       0
Winner           0
Host_Country     0
Venue_Team1      0
Venue_Team2      0
Innings_Team1    0
Innings_Team2    0
dtype: int64

In [6]:
df.columns

Index(['Unnamed: 0', 'Scorecard', 'Team 1', 'Team 2', 'Margin', 'Ground',
       'Match Date', 'Winner', 'Host_Country', 'Venue_Team1', 'Venue_Team2',
       'Innings_Team1', 'Innings_Team2'],
      dtype='object')

In [7]:
df = df[['Unnamed: 0','Match Date', 'Scorecard', 'Team 1', 'Team 2', 'Ground', 'Winner', 'Host_Country',
    'Venue_Team1', 'Venue_Team2','Innings_Team1', 'Innings_Team2', 'Margin']]

In [8]:
df.head(1)

Unnamed: 0 Match Date Scorecard     Team 1   Team 2     Ground     Winner  \
0           0  05-Jan-71   ODI # 1  Australia  England  Melbourne  Australia   

  Host_Country Venue_Team1 Venue_Team2 Innings_Team1 Innings_Team2  \
0    Australia        Home        Away        Second         First   

            Margin  
0  Winner2ndInning

In [9]:
df.shape

(7494, 13)

In [10]:
x = df.iloc[:,3:12].values
y = df.iloc[:,12].values

In [11]:
x,y

(array([['Australia', 'England', 'Melbourne', ..., 'Away', 'Second',
         'First'],
        ['England', 'Australia', 'Manchester', ..., 'Away', 'Second',
         'First'],
        ['England', 'Australia', "Lord's", ..., 'Away', 'First', 'Second'],
        ...,
        ['Namibia', 'Hong Kong', 'Mumbai', ..., 'Neutral', 'Second',
         'First'],
        ['U.S.A.', 'Bermuda', 'Mumbai', ..., 'Neutral', 'Second', 'First'],
        ['Namibia', 'East Africa', 'Mumbai', ..., 'Neutral', 'Second',
         'First']], dtype=object),
 array(['Winner2ndInning', 'Winner2ndInning', 'Winner2ndInning', ...,
        'Winner2ndInning', 'Winner2ndInning', 'Winner1stInning'],
       dtype=object))

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [13]:
for i in range(9):
    x[:,i] = le.fit_transform(x[:,i])
x

array([[1, 6, 96, ..., 0, 1, 0],
       [6, 1, 94, ..., 0, 1, 0],
       [6, 1, 92, ..., 0, 0, 1],
       ...,
       [11, 7, 103, ..., 2, 1, 0],
       [20, 3, 103, ..., 2, 1, 0],
       [11, 5, 103, ..., 2, 1, 0]], dtype=object)

In [14]:
y = le.fit_transform(y)
y

array([1, 1, 1, ..., 1, 1, 0])

In [15]:
pd.DataFrame(x).to_csv(r'D:\E\Courses\ML_Practice\le_x.csv')

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=0, test_size=0.2)

In [17]:
len(x_train), len(x_test), len(y_train), len(y_test)

(5995, 1499, 5995, 1499)

#### Applying Logisticregression for prediction

In [18]:
from sklearn.linear_model import LogisticRegression

lr_classifier = LogisticRegression()
lr_classifier.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
y_pred_lr = lr_classifier.predict(x_test)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [21]:
confusion_matrix(y_test, y_pred_lr)

array([[252, 507],
       [225, 515]], dtype=int64)

In [22]:
accuracy_score(y_test, y_pred_lr)

0.5116744496330887

In [23]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.53      0.33      0.41       759
           1       0.50      0.70      0.58       740

    accuracy                           0.51      1499
   macro avg       0.52      0.51      0.50      1499
weighted avg       0.52      0.51      0.50      1499



#### Applying decision tree

In [38]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [39]:
y_pred_dt = dt_classifier.predict(x_test)
y_pred_dt

array([1, 1, 0, ..., 1, 0, 0])

In [40]:
confusion_matrix(y_test, y_pred_dt)

array([[693,  66],
       [ 63, 677]], dtype=int64)

In [41]:
accuracy_score(y_test, y_pred_dt)

0.9139426284189459

In [28]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       0.91      0.91      0.91       759
           1       0.91      0.91      0.91       740

    accuracy                           0.91      1499
   macro avg       0.91      0.91      0.91      1499
weighted avg       0.91      0.91      0.91      1499



#### Applying Random Forest

In [29]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(n_estimators=10)
rf_classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [31]:
y_pred_rf = rf_classifier.predict(x_test)
y_pred_rf

array([1, 1, 0, ..., 1, 0, 0])

In [32]:
confusion_matrix(y_test, y_pred_rf)

array([[743,  16],
       [ 18, 722]], dtype=int64)

In [33]:
accuracy_score(y_test, y_pred_rf)

0.9773182121414277

##### applying gridsearchcv to check if we can import random forest model

In [43]:
from sklearn.model_selection import GridSearchCV

lst = list(range(1,25))
parameters = [{'n_estimators':lst}]

In [44]:
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=parameters, scoring='accuracy', n_jobs=-1)

grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_param = grid_search.best_params_

In [45]:
best_accuracy, best_param

(0.9808173477898249, {'n_estimators': 23})

In [46]:
rf_classifier2 = RandomForestClassifier(n_estimators=23)
rf_classifier2.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=23,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [47]:
y_pred_rf2 = rf_classifier2.predict(x_test)
y_pred_rf2

array([1, 1, 0, ..., 1, 0, 0])

In [48]:
confusion_matrix(y_test, y_pred_rf2)

array([[739,  20],
       [ 15, 725]], dtype=int64)

In [49]:
accuracy_score(y_test, y_pred_rf2)

0.9766511007338226

#### Applying cross validation to check how good is the model

In [50]:
from sklearn.model_selection import cross_val_score

accuracies = cross_val_score(estimator=rf_classifier, X=x_train, y=y_train, cv=10)

In [51]:
accuracies

array([0.97833333, 0.985     , 0.97333333, 0.985     , 0.98      ,
       0.96994992, 0.97829716, 0.97662771, 0.97996661, 0.97662771])

In [53]:
accuracies.mean()

0.9783135781858652