### Classification

####### classification is a type of supervised machine learning algorithm, where the predictions will be in a descrete output. 

eg: rain prediction, customer will buy product or not, etc

(We have more classification problem than regression problem related to business. approximately 7 out of 10)

##### 6 algorithms are using for classification
----------------------------------------

## 1. Logistic Regression

####### Sigmoid Function is using to generate logistic regression

Probability (P) = 1/(1 + e^(-y))

if we derive y from above equation

y = log(P/(1-P))

--This can be applies for y = mx+c

As probability will be between 0 & 1 we can fix a range (0.5 or 0.4 or 0.8) for getting output as zero or 1.

## 2. K-Nearest Neighbour

####### This algorithm works based on distances.

Euclidian Distance = sqrt((X2 - X1)^2 + (Y2 - Y1)^2)

It find the distance between all existing data points with the datapoints for prediction.
It takes the number of neighbours (we can decide it) and predict the value as whichever option is higher within neighbours. The number of neighbours deciding should be odd number (if its even both conditions probability can be equal)
Number of neighbours can be the square root of number of records.

It is a time consuming algorithm.

## 3. Naive Bayes (Bayes theorem for probability)

####### Bayes theorem works on conditional probability

P(A|B) = P(B|A) * P(A)/ P(B)

It works faster than K-Nearest Neighbour algorithm

## 4. Support Vector Machine

####### This algorithm splits the entire data into two using 1 point from each type of data. It will select the line to split with equal distance from both nearest points of each data segments. The two nearest data points are known as vectors.
The line through which it cuts the data into 2 is known as hyper plane.

The splitting of the data into 2 can be in different methods

    4.1 : Linear kernel
        - Splits the data into 2 with a straight line.
    4.2 : Sigmoid kernel
        - Splits the data into 2 with help of a sigmoid kernel.
    4.3 : Polynomial kernel
        - Splits the data into 2 with a polynomial curve.
    4.4 : Radial basis function kernel
        - Radially (inside and outside circles) splits the data into 2.

## 5. Decesion Tree

####### Decesion Tree algorithm works on entropy. Entropy is known as major of impurity. Entropy will be varying from zero to one. Zero means no impurity and one means maximum impurity.

eg: If there is a basket with 50 apple and 50 banana, while taking one and it tobe an apple- the entropy is 50%

Equation for entropy:

Entropy(S) = -P(Yes)*log2P(Yes) -P(No)*log2P(No)


Information Gain helps to understand which column is more relevent to predict the output. Equation as below.

Information Gain (IG) = Entropy(S) - (Weighted average * Entropy of each feature)

## 6. Random Forest

####### It runs multiple decision tree within, then go with majority to decide yes or no.

### Confusion Matrix

###### Confusion matrix helps to find the accuracy of a classifier model. The confusion matrix will be showing true positive, true negative, false positive , false negative numbers.

Accuracy = (TP+TN)/(TP+TN+FP+FN)

### Applying above 6 algorithms to a data to predict if customer will buy product

In [2]:
import pandas as pd
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [4]:
df = pd.read_csv(r'D:\Edureka\Social_Network_Ads.csv')

In [5]:
print(df.shape)
df.head()

(400, 5)


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [8]:
x = df.iloc[:,2:4].values  # independant variables

In [10]:
y = df.iloc[:,-1:].values   # dependant variables

In [11]:
x[:2]   #one is age, one is salary ... there is a huge scale difference

array([[   19, 19000],
       [   35, 20000]], dtype=int64)

In [13]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
x = sc_x.fit_transform(x)

# using StandardScaler converted both variables into same scale

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [15]:
print(len(x_train), len(x_test), len(y_train), len(y_test))

280 120 280 120


#### Applying Logistic regression to predict if customer will buy product

In [16]:
from sklearn.linear_model import LogisticRegression

logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [27]:
y_predict_logistic = logmodel.predict(x_test)

In [29]:
y_predict_logistic

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [30]:
sum(y_predict_logistic)

44

In [24]:
sum(y_test)

array([45], dtype=int64)

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_predict_logistic)

array([[66,  9],
       [10, 35]], dtype=int64)

In [36]:
(66+35)/120  #accuracy

0.8416666666666667

#### Applying K-nearest neighbour to predict if customer will buy product

In [25]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier()
# this algorithm need some parameters and it is known as hyper parameters. default value of n_neighbours = 5.
# we can use grid search algorithm to find the best value for n_neighbours.
#Another industry standard method is to take the square root of the length of array (no. of data) and make it odd

classifier_knn.fit(x_train, y_train)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  import sys


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [31]:
y_predict_knn = classifier_knn.predict(x_test)

In [32]:
y_predict_knn

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [33]:
sum(y_predict_knn)

51

In [35]:
confusion_matrix(y_test, y_predict_knn)

array([[66,  9],
       [ 3, 42]], dtype=int64)

In [37]:
(66+42)/120  #accuracy

0.9

#### Applying Naive Bayes algorithm for prediction

In [38]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None)

In [40]:
y_predict_nb = classifier_nb.predict(x_test)

In [41]:
y_predict_nb

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [42]:
sum(y_predict_nb)

44

In [43]:
confusion_matrix(y_test, y_predict_nb)

array([[67,  8],
       [ 9, 36]], dtype=int64)

In [44]:
# accuracy

(67+36)/120

0.8583333333333333

#### Applying Support Vector Machine algorithm for prediction

we are applying 4 different kernels inside SVM

###### Support vector machine - linear kernel

In [45]:
from sklearn.svm import SVC

classifier_svm_lin = SVC(kernel='linear')
classifier_svm_lin.fit(x_train, y_train)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [47]:
y_predict_svm_lin = classifier_svm_lin.predict(x_test)

In [48]:
y_predict_svm_lin

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [49]:
sum(y_predict_svm_lin)

43

In [50]:
confusion_matrix(y_test, y_predict_svm_lin)

array([[66,  9],
       [11, 34]], dtype=int64)

In [51]:
# accuracy

(66+34)/120

0.8333333333333334

###### Support vector machine - rbf(radial basis function) kernel

In [52]:
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train, y_train)
y_predict_svm_rbf = classifier_svm_rbf.predict(x_test)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [53]:
y_predict_svm_rbf

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [54]:
sum(y_predict_svm_rbf)

49

In [55]:
confusion_matrix(y_test, y_predict_svm_rbf)

array([[66,  9],
       [ 5, 40]], dtype=int64)

In [56]:
# accuracy

(66+40)/120

0.8833333333333333

###### Support vector machine - sigmoid kernel

In [57]:
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train, y_train)
y_predict_svm_sigmoid = classifier_svm_sigmoid.predict(x_test)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [58]:
y_predict_svm_sigmoid

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [59]:
sum(y_predict_svm_sigmoid)

47

In [60]:
confusion_matrix(y_test, y_predict_svm_sigmoid)

array([[57, 18],
       [16, 29]], dtype=int64)

In [61]:
# accuracy

(57+29)/120

0.7166666666666667

###### Support vector machine - polynomial kernel

In [62]:
classifier_svm_poly = SVC(kernel='poly')
classifier_svm_poly.fit(x_train, y_train)
y_predict_svm_poly = classifier_svm_poly.predict(x_test)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [63]:
y_predict_svm_poly

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [64]:
sum(y_predict_svm_poly)

32

In [65]:
confusion_matrix(y_test, y_predict_svm_poly)

array([[72,  3],
       [16, 29]], dtype=int64)

In [66]:
# accuracy

(72+29)/120

0.8416666666666667

#### Applying Decesion Tree classification algorithm for prediction

In [67]:
from sklearn.tree import DecisionTreeClassifier

classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [69]:
y_predict_dt = classifier_dt.predict(x_test)

In [70]:
y_predict_dt

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [71]:
sum(y_predict_dt)

49

In [73]:
confusion_matrix(y_test, y_predict_dt)

array([[66,  9],
       [ 5, 40]], dtype=int64)

In [74]:
# accuracy

(66+40)/120

0.8833333333333333

#### Applying Random Forest classification algorithm for prediction

In [75]:
from sklearn.ensemble import RandomForestClassifier
classifier_rt = RandomForestClassifier(n_estimators=5, criterion='entropy')

# to find best value for n_estimator, grid search algorithm is a good method. Here we are assuming 5 trees to run

classifier_rt.fit(x_train, y_train)

C:\Users\sreeraj.va\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [77]:
y_predict_rt = classifier_rt.predict(x_test)

In [78]:
y_predict_rt

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [79]:
sum(y_predict_rt)

50

In [80]:
confusion_matrix(y_test, y_predict_rt)

array([[65, 10],
       [ 5, 40]], dtype=int64)

In [81]:
# accuracy
(65+40)/120

0.875

##### Note:-

####### Accuracy wise K-Nearest neighbor algorithm is the best.

But it depends on business needs to take which one.
If it is for a promotion or a call center call for conversion, we can even consolidate all the positives from all models and give to business.