#### Liniar Regression with Encoding and multiple independand variables & Statsmodels module

In [3]:
import pandas as pd
import numpy as np  # imported modles

In [4]:
df = pd.read_csv(r'D:\Edureka\50_Startups.csv')
print(df.shape)
df.head(2)  # importing dataset

(50, 5)


R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder  # import modules for encoding

In [6]:
x = df.iloc[:, 0:4].values
y = df.iloc[:, -1:].values
print(x[:3])
print(y[:3])
print(len(x), len(y))  # converting dependent and independant variables into array

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']]
[[192261.83]
 [191792.06]
 [191050.39]]
50 50


In [7]:
labelencoder = LabelEncoder()
x[:,3] = labelencoder.fit_transform(x[:,3])  # applied label encoding

In [8]:
oht = OneHotEncoder(categorical_features=[3])
x = oht.fit_transform(x).toarray()   # applied onehotencoding

In [9]:
x[:2]

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05]])

In [10]:
pd.DataFrame(x).head(3)  # x after applying encoding

0    1    2          3          4          5
0  0.0  0.0  1.0  165349.20  136897.80  471784.10
1  1.0  0.0  0.0  162597.70  151377.59  443898.53
2  0.0  1.0  0.0  153441.51  101145.55  407934.54

###### Dummy Variables:
  If we are getting 'n' variables after onehot encoding, we need to use only (n-1) variables for prediction. This is to avoid 
  multicolinearity.

In [11]:
# removing index-0 column from x

x = x[:, 1:]

In [12]:
pd.DataFrame(x).head(3)

0    1          2          3          4
0  0.0  1.0  165349.20  136897.80  471784.10
1  0.0  0.0  162597.70  151377.59  443898.53
2  1.0  0.0  153441.51  101145.55  407934.54

####### now we have to create prediction model with x & y

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)
print(len(x_train), len(x_test), len(y_train), len(y_test))

35 15 35 15


In [14]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
y_predict = lin_reg.predict(x_test)

In [16]:
for i in range(len(y_test)):
    print(y_test[i], y_predict[i])

[81005.76] [85569.24558015]
[132602.65] [149962.82856893]
[96778.92] [98994.65622413]
[144259.4] [136072.24003493]
[141585.52] [129674.50113853]
[14681.4] [51817.06610969]
[149759.96] [154905.03656853]
[107404.34] [104521.81324636]
[182901.99] [171744.31113609]
[97483.56] [99146.61829113]
[134307.35] [128640.01350358]
[71498.49] [73016.04957207]
[99937.59] [101248.33740485]
[152211.77] [150939.2119719]
[129917.04] [145492.35487831]


In [17]:
from sklearn.metrics import r2_score
r2_score(y_test, y_predict)   # r^2 value

0.9005221632323388

In [18]:
lin_reg.coef_   #slopes (m)

array([[-5.01635637e+02, -1.31361015e+03,  7.88981921e-01,
        -1.48217779e-02,  2.17694543e-02]])

In [19]:
lin_reg.intercept_  # contacnt (c)

array([52567.58115146])

#### Regression using statsmodel module

In [20]:
#!pip install statsmodels

In [1]:
#!pip3 install statsmodels==0.10.0rc2 --pre --user

In [21]:
import statsmodels.api as sm

In [22]:
regressor_OLS = sm.OLS(endog=y_train, exog=x_train).fit()

In [23]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.989
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              523.7
Date:                Tue, 11 Feb 2020   Prob (F-statistic):                    3.14e-28
Time:                        17:57:55   Log-Likelihood:                         -379.81
No. Observations:                  35   AIC:                                      769.6
Df Residuals:                      30   BIC:                                      777.4
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          6537.5022   5795.104      1.128      0.268   -5297.680    1.84e+04
x2          9022.2674   5270.217      1.712      0.097   -1740.951    1.98e+04
x3             0.7245      0.070     10.321      0.000       0.581       0.868
x4             0.3135      0.039      7.992      0.000       0.233       0.394
x5             0.0642      0.024      2.667      0.012       0.015       0.113
==============================================================================
Omnibus:                        0.402   Durbin-Watson:                   1.310
Prob(Omnibus):                  0.818   Jarque-Bera (JB):                0.545
Skew:                           0.018   Prob(JB):                        0.761
Kurtosis:                       2.390   Cond. No.                     8.40e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.4e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [24]:
# in the above details intercept is not available. To get intercept we need to add a column with 1 in x_train (as coefficiant 
# of c is 1 in y = mx+c)

x_train = np.append(arr=x_train, values = np.ones((35,1)).astype(int), axis=1)

In [25]:
pd.DataFrame(x_train).head(3)

0    1         2          3          4    5
0  1.0  0.0   1315.46  115816.21  297114.46  1.0
1  0.0  0.0  76253.86  113867.30  298664.47  1.0
2  1.0  0.0  73994.56  122782.75  303319.26  1.0

In [26]:
regressor_OLS = sm.OLS(endog=y_train, exog=x_train).fit()

In [27]:
regressor_OLS.summary()

#now we got one more line as contant in the details

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.964
Method:                 Least Squares   F-statistic:                     182.8
Date:                Tue, 11 Feb 2020   Prob (F-statistic):           5.36e-21
Time:                        18:06:03   Log-Likelihood:                -359.49
No. Observations:                  35   AIC:                             731.0
Df Residuals:                      29   BIC:                             740.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          -501.6356   3414.349     -0.147      0.884   -7484.763    6481.492
x2         -1313.6101   3267.542     -0.402      0.691   -7996.484    5369.264
x3             0.7890      0.041     19.356      0.000       0.706       0.872
x4            -0.0148      0.047     -0.316      0.754      -0.111       0.081
x5             0.0218      0.015      1.481      0.150      -0.008       0.052
const       5.257e+04   6591.020      7.976      0.000    3.91e+04     6.6e+04
==============================================================================
Omnibus:                        1.103   Durbin-Watson:                   1.844
Prob(Omnibus):                  0.576   Jarque-Bera (JB):                1.111
Skew:                           0.348   Prob(JB):                        0.574
Kurtosis:                       2.474   Cond. No.                     1.49e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

##### R^2 value and adjusted R^2 value

####### To check the accuracy of a model, adjusted R^2 value is better than R^2 value.
Reason: R^2 value may increase when we have more independant variables, even if the independant variable actually deos not effect the dependant variable.

Adjusted R^2 value does not have the tendency, because of below calculation (Multiplying it with the fraction with value below 1)

Adjusted R^2 value = 1 - (1-R^2)[(n-1)/(n-(k+1))]

##### P value

####### If P-value is near to zero, the model is very good. If P-value increasing towards one, we have to reject it.

Industry standard : P-value should be less than 0.05

In [28]:
#As per the P-value in the statsmodel summary only R & D spend (x3) affects the profit.