In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [39]:
f = open(r'E:\classification\adult_data_uci\old.adult.names', 'r')

In [40]:
f.readlines()

['1. Title of Database: adult\n',
 '2. Sources:\n',
 '   (a) Original owners of database (name/phone/snail address/email address)\n',
 '       US Census Bureau.\n',
 '   (b) Donor of database (name/phone/snail address/email address)\n',
 '       Ronny Kohavi and Barry Becker, \n',
 '       Data Mining and Visualization\n',
 '       Silicon Graphics.\n',
 '       e-mail: ronnyk@sgi.com\n',
 '   (c) Date received (databases may change over time without name change!)\n',
 '       05/19/96\n',
 '3. Past Usage:\n',
 '   (a) Complete reference of article where it was described/used\n',
 '        @inproceedings{kohavi-nbtree,\n',
 '           author={Ron Kohavi},\n',
 '           title={Scaling Up the Accuracy of Naive-Bayes Classifiers: a \n',
 '                  Decision-Tree Hybrid},\n',
 '           booktitle={Proceedings of the Second International Conference on\n',
 '                      Knowledge Discovery and Data Mining},\n',
 '           year = 1996,\n',
 '           pages={to appe

In [41]:
col = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'class']

In [42]:
df = pd.read_csv(r'E:\classification\adult_data_uci\adult.data', header=None)

In [43]:
df

0                  1       2            3   4                    5   \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                       6               7       8        9      10  11  12  \
0            Adm-clerical   Not-in-family   White     Male   2174   0  40   
1         Exec-managerial         Husband   White     Male      0   0  13   
2       Handlers-cleaners   Not-in-family   White     Male      0   0  40   
3       Handlers-cleaners         Husband   Black     Male      0   0  40   
4          Prof-specialty            Wife   Black   Female      0   0  40   
...                   ...             ...     ...      ...    ...  ..  ..   
32556        Tech-support            Wife   White   Female      0   0  38   
32557   Machine-op-inspct         Husband   White     Male      0   0  40   
32558        Adm-clerical       Unmarried   White   Female      0   0  40   
32559        Adm-clerical       Own-child   White     Male      0   0  20   
32560     Exec-managerial            Wife   White   Female  15024   0  40   

                   13      14  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3       United-States   <=50K  
4                Cuba   <=50K  
...               ...     ...  
32556   United-States   <=50K  
32557   United-States    >50K  
32558   United-States   <=50K  
32559   United-States   <=50K  
32560   United-States    >50K  

[32561 rows x 15 columns]

In [44]:
df.columns = col

In [45]:
df.head(1)

age   workclass  fnlwgt   education  education-num  marital-status  \
0   39   State-gov   77516   Bachelors             13   Never-married   

      occupation    relationship    race    sex  capital-gain  capital-loss  \
0   Adm-clerical   Not-in-family   White   Male          2174             0   

   hours-per-week  native-country   class  
0              40   United-States   <=50K

In [46]:
df.describe().round(1)

age     fnlwgt  education-num  capital-gain  capital-loss  \
count  32561.0    32561.0        32561.0       32561.0       32561.0   
mean      38.6   189778.4           10.1        1077.6          87.3   
std       13.6   105550.0            2.6        7385.3         403.0   
min       17.0    12285.0            1.0           0.0           0.0   
25%       28.0   117827.0            9.0           0.0           0.0   
50%       37.0   178356.0           10.0           0.0           0.0   
75%       48.0   237051.0           12.0           0.0           0.0   
max       90.0  1484705.0           16.0       99999.0        4356.0   

       hours-per-week  
count         32561.0  
mean             40.4  
std              12.3  
min               1.0  
25%              40.0  
50%              40.0  
75%              45.0  
max              99.0

In [47]:
df.describe(include='all').round(1)

age workclass     fnlwgt education  education-num  \
count   32561.0     32561    32561.0     32561        32561.0   
unique      NaN         9        NaN        16            NaN   
top         NaN   Private        NaN   HS-grad            NaN   
freq        NaN     22696        NaN     10501            NaN   
mean       38.6       NaN   189778.4       NaN           10.1   
std        13.6       NaN   105550.0       NaN            2.6   
min        17.0       NaN    12285.0       NaN            1.0   
25%        28.0       NaN   117827.0       NaN            9.0   
50%        37.0       NaN   178356.0       NaN           10.0   
75%        48.0       NaN   237051.0       NaN           12.0   
max        90.0       NaN  1484705.0       NaN           16.0   

             marital-status       occupation relationship    race    sex  \
count                 32561            32561        32561   32561  32561   
unique                    7               15            6       5      2   
top      Married-civ-spouse   Prof-specialty      Husband   White   Male   
freq                  14976             4140        13193   27816  21790   
mean                    NaN              NaN          NaN     NaN    NaN   
std                     NaN              NaN          NaN     NaN    NaN   
min                     NaN              NaN          NaN     NaN    NaN   
25%                     NaN              NaN          NaN     NaN    NaN   
50%                     NaN              NaN          NaN     NaN    NaN   
75%                     NaN              NaN          NaN     NaN    NaN   
max                     NaN              NaN          NaN     NaN    NaN   

        capital-gain  capital-loss  hours-per-week  native-country   class  
count        32561.0       32561.0         32561.0           32561   32561  
unique           NaN           NaN             NaN              42       2  
top              NaN           NaN             NaN   United-States   <=50K  
freq             NaN           NaN             NaN           29170   24720  
mean          1077.6          87.3            40.4             NaN     NaN  
std           7385.3         403.0            12.3             NaN     NaN  
min              0.0           0.0             1.0             NaN     NaN  
25%              0.0           0.0            40.0             NaN     NaN  
50%              0.0           0.0            40.0             NaN     NaN  
75%              0.0           0.0            45.0             NaN     NaN  
max          99999.0        4356.0            99.0             NaN     NaN

In [48]:
unique_value_dict = {}
for i in df.columns:
    unique_value_dict[i] = len(list(df[i].unique()))

In [49]:
print(unique_value_dict)

{'age': 73, 'workclass': 9, 'fnlwgt': 21648, 'education': 16, 'education-num': 16, 'marital-status': 7, 'occupation': 15, 'relationship': 6, 'race': 5, 'sex': 2, 'capital-gain': 119, 'capital-loss': 92, 'hours-per-week': 94, 'native-country': 42, 'class': 2}


In [50]:
df.shape

(32561, 15)

In [51]:
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
class             0
dtype: int64

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loss    32561 non-null  int64 
 12  hours-per-week  32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  class           32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [53]:
df2 = df.copy()

In [54]:
le_col = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'class']

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
le = LabelEncoder()

In [57]:
for i in le_col:
    df2[i] = le.fit_transform(df2[i])

In [58]:
df2.head()

age  workclass  fnlwgt  education  education-num  marital-status  \
0   39          7   77516          9             13               4   
1   50          6   83311          9             13               2   
2   38          4  215646         11              9               0   
3   53          4  234721          1              7               2   
4   28          4  338409          9             13               2   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           1             1     4    1          2174             0   
1           4             0     4    1             0             0   
2           6             1     4    1             0             0   
3           6             0     2    1             0             0   
4          10             5     2    0             0             0   

   hours-per-week  native-country  class  
0              40              39      0  
1              13              39      0  
2              40              39      0  
3              40              39      0  
4              40               5      0

In [59]:
df2.corr().round(2)

age  workclass  fnlwgt  education  education-num  \
age             1.00       0.00   -0.08      -0.01           0.04   
workclass       0.00       1.00   -0.02       0.02           0.05   
fnlwgt         -0.08      -0.02    1.00      -0.03          -0.04   
education      -0.01       0.02   -0.03       1.00           0.36   
education-num   0.04       0.05   -0.04       0.36           1.00   
marital-status -0.27      -0.06    0.03      -0.04          -0.07   
occupation     -0.02       0.25    0.00      -0.02           0.11   
relationship   -0.26      -0.09    0.01      -0.01          -0.09   
race            0.03       0.05   -0.02       0.01           0.03   
sex             0.09       0.10    0.03      -0.03           0.01   
capital-gain    0.08       0.03    0.00       0.03           0.12   
capital-loss    0.06       0.01   -0.01       0.02           0.08   
hours-per-week  0.07       0.14   -0.02       0.06           0.15   
native-country -0.00      -0.01   -0.05       0.06           0.05   
class           0.23       0.05   -0.01       0.08           0.34   

                marital-status  occupation  relationship  race   sex  \
age                      -0.27       -0.02         -0.26  0.03  0.09   
workclass                -0.06        0.25         -0.09  0.05  0.10   
fnlwgt                    0.03        0.00          0.01 -0.02  0.03   
education                -0.04       -0.02         -0.01  0.01 -0.03   
education-num            -0.07        0.11         -0.09  0.03  0.01   
marital-status            1.00       -0.01          0.19 -0.07 -0.13   
occupation               -0.01        1.00         -0.08  0.01  0.08   
relationship              0.19       -0.08          1.00 -0.12 -0.58   
race                     -0.07        0.01         -0.12  1.00  0.09   
sex                      -0.13        0.08         -0.58  0.09  1.00   
capital-gain             -0.04        0.03         -0.06  0.01  0.05   
capital-loss             -0.03        0.02         -0.06  0.02  0.05   
hours-per-week           -0.19        0.08         -0.25  0.04  0.23   
native-country           -0.02       -0.01         -0.01  0.14 -0.01   
class                    -0.20        0.08         -0.25  0.07  0.22   

                capital-gain  capital-loss  hours-per-week  native-country  \
age                     0.08          0.06            0.07           -0.00   
workclass               0.03          0.01            0.14           -0.01   
fnlwgt                  0.00         -0.01           -0.02           -0.05   
education               0.03          0.02            0.06            0.06   
education-num           0.12          0.08            0.15            0.05   
marital-status         -0.04         -0.03           -0.19           -0.02   
occupation              0.03          0.02            0.08           -0.01   
relationship           -0.06         -0.06           -0.25           -0.01   
race                    0.01          0.02            0.04            0.14   
sex                     0.05          0.05            0.23           -0.01   
capital-gain            1.00         -0.03            0.08           -0.00   
capital-loss           -0.03          1.00            0.05            0.00   
hours-per-week          0.08          0.05            1.00           -0.00   
native-country         -0.00          0.00           -0.00            1.00   
class                   0.22          0.15            0.23            0.02   

                class  
age              0.23  
workclass        0.05  
fnlwgt          -0.01  
education        0.08  
education-num    0.34  
marital-status  -0.20  
occupation       0.08  
relationship    -0.25  
race             0.07  
sex              0.22  
capital-gain     0.22  
capital-loss     0.15  
hours-per-week   0.23  
native-country   0.02  
class            1.00

In [60]:
df2.shape

(32561, 15)

In [61]:
x = df2.iloc[:,:14].values
y = df2.iloc[:,14].values

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1, stratify=y)

In [64]:
len(x_train), len(x_test), len(y_train), len(y_test)

(26048, 6513, 26048, 6513)

###### logistic regression

In [65]:
from sklearn.linear_model import LogisticRegression

In [66]:
lr = LogisticRegression(max_iter=100000)
lr.fit(x_train, y_train)

LogisticRegression(max_iter=100000)

In [67]:
y_pred_lr = lr.predict(x_test)

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [69]:
confusion_matrix(y_test, y_pred_lr)

array([[4645,  300],
       [1106,  462]], dtype=int64)

In [70]:
accuracy_score(y_test, y_pred_lr)

0.7841240595731613

#### decision tree

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [36]:
y_pred_dt = dt.predict(x_test)

In [37]:
confusion_matrix(y_test, y_pred_dt)

array([[4293,  652],
       [ 638,  930]], dtype=int64)

In [38]:
accuracy_score(y_test, y_pred_dt)

0.8019345923537541

###### grid search with decision tree

In [88]:
from sklearn.model_selection import GridSearchCV

In [40]:
parameter = [{'criterion':['gini', 'entropy'], 'splitter':['best', 'random'], 'max_depth':list(range(11)), 'min_samples_split':list(range(2,11))}]

In [41]:
grid_search = GridSearchCV(estimator=dt, param_grid=parameter, n_jobs=-1, scoring='accuracy')
grid_search = grid_search.fit(x_train, y_train)

In [42]:
grid_search.best_params_

{'criterion': 'entropy',
 'max_depth': 7,
 'min_samples_split': 6,
 'splitter': 'best'}

In [43]:
grid_search.best_score_

0.8554590773609385

In [44]:
dt2 = DecisionTreeClassifier(max_depth=7, min_samples_split=10)
dt2.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=7, min_samples_split=10)

In [45]:
y_pred_dt2 = dt2.predict(x_test)

In [46]:
confusion_matrix(y_test, y_pred_dt2)

array([[4718,  227],
       [ 746,  822]], dtype=int64)

In [47]:
accuracy_score(y_test, y_pred_dt2)

0.8506064793489944

##### random forest

In [48]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [49]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [50]:
y_pred_rf = rf.predict(x_test)

In [51]:
confusion_matrix(y_test, y_pred_rf)

array([[4612,  333],
       [ 598,  970]], dtype=int64)

In [52]:
accuracy_score(y_test, y_pred_rf)

0.8570551205281745

##### grid search with random forest

In [53]:
parameter = [{'n_estimators':list(range(2,10)), 'criterion':['gini', 'entropy'], 'max_depth':list(range(6)), 'min_samples_split':list(range(2,6))}]

In [54]:
grid_search = GridSearchCV(estimator=rf, param_grid=parameter, scoring='accuracy', n_jobs=-1)
grid_search = grid_search.fit(x_train, y_train)

In [55]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 5,
 'min_samples_split': 4,
 'n_estimators': 7}

In [56]:
grid_search.best_score_

0.8498155598847262

##### SVM

In [71]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [73]:
x

array([[    39,      7,  77516, ...,      0,     40,     39],
       [    50,      6,  83311, ...,      0,     13,     39],
       [    38,      4, 215646, ...,      0,     40,     39],
       ...,
       [    58,      4, 151910, ...,      0,     40,     39],
       [    22,      4, 201490, ...,      0,     20,     39],
       [    52,      5, 287927, ...,      0,     40,     39]], dtype=int64)

In [74]:
x = sc.fit_transform(x)

In [75]:
x

array([[ 0.03067056,  2.15057856, -1.06361075, ..., -0.21665953,
        -0.03542945,  0.29156857],
       [ 0.83710898,  1.46373585, -1.008707  , ..., -0.21665953,
        -2.22215312,  0.29156857],
       [-0.04264203,  0.09005041,  0.2450785 , ..., -0.21665953,
        -0.03542945,  0.29156857],
       ...,
       [ 1.42360965,  0.09005041, -0.35877741, ..., -0.21665953,
        -0.03542945,  0.29156857],
       [-1.21564337,  0.09005041,  0.11095988, ..., -0.21665953,
        -1.65522476,  0.29156857],
       [ 0.98373415,  0.77689313,  0.92989258, ..., -0.21665953,
        -0.03542945,  0.29156857]])

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, stratify=y, test_size=.2)

In [81]:
from sklearn.svm import SVC

In [82]:
sv = SVC(kernel='linear')

In [83]:
sv.fit(x_train, y_train)

SVC(kernel='linear')

In [84]:
y_pred_sv = sv.predict(x_test)

In [85]:
confusion_matrix(y_test, y_pred_sv)

array([[4808,  137],
       [1075,  493]], dtype=int64)

In [86]:
accuracy_score(y_test, y_pred_sv)

0.8139106402579457

In [87]:
parameter = [{'C':[1,2,3,4,5], 'kernel':['linear', 'poly', 'rbf', 'sigmoid'], 'degree':[2,3,4,5], 'gamma':['scale', 'auto']}]

In [89]:
grid_search = GridSearchCV(estimator=sv, param_grid=parameter, scoring='accuracy', n_jobs=-1)
grid_search = grid_search.fit(x_train, y_train)

In [91]:
grid_search.best_params_

{'C': 4, 'degree': 2, 'gamma': 'scale', 'kernel': 'rbf'}

In [92]:
grid_search.best_score_

0.851428197689736

In [93]:
sv = SVC(kernel='rbf', gamma='scale', C=4, degree=2)

In [94]:
sv.fit(x_train, y_train)

SVC(C=4, degree=2)

In [95]:
y_pred_sv = sv.predict(x_test)

In [96]:
confusion_matrix(y_test, y_pred_sv)

array([[4621,  324],
       [ 709,  859]], dtype=int64)

In [97]:
accuracy_score(y_test, y_pred_sv)

0.8413941348073085

In [98]:
from sklearn.model_selection import cross_val_score

In [99]:
accuracies = cross_val_score(estimator=sv, X=x_train, y=y_train, cv=10)

In [100]:
accuracies

array([0.85028791, 0.84491363, 0.84990403, 0.86257198, 0.85297505,
       0.84491363, 0.84145873, 0.86026871, 0.84485407, 0.85560676])

In [102]:
accuracies.mean()

0.8507754495519958